{% set version = "1.2.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bsda
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/BSDA_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/BSDA/BSDA_{{ version }}.tar.gz
  sha256: e2f1cb8fe07e8bdf1a813f20519bad4d1836d6945fc49c4dae40bf99031c8e6d

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]

  host:
    - r-base
    - r-e1071
    - r-lattice

  run:
    - r-base
    - r-e1071
    - r-lattice

test:
  commands:
    - $R -e "library('BSDA')"           # [not win]
    - "\"%R%\" -e \"library('BSDA')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=BSDA
  license: GPL-2.0-or-later
  summary: Data sets for book "Basic Statistics and Data Analysis" by Larry J. Kitchens.

  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn
